version: "3.5"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: postgres

user:
  image: shopping/user-api
  ports:
    - "8080:8080"
environment:
  POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
depends_on:
  - postgres

product:
  image: shopping/product-api
  ports:
    - "8081:8081"
  environment:
    POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  depends_on:
    - postgres

shopping:
  image: shopping/shopping-api
  ports:
    - "8082:8082"
  environment:
    POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
    POSTGRES_USER: postgres

gateway:
  image: shopping/gateway
  ports:
    - "8084:8084"
  environment:
    PRODUCT_API_URL: http://product:8081
    USER_API_URL: http://user:8080
    SHOPPING_API_URL: http://shopping:8082
  depends_on:
    - postgres